{
 "title": "ipld-eth-server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Websocket Connection Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ipld_eth_server_ws_count" }
   ]
  },
  {
   "title": "IPC Connection Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "ipld_eth_server_ipc_count" }
   ]
  },
  {
   "title": "HTTP requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ipld_eth_server_http_count[1m])"
    }
   ]
  },
  {
   "title": "HTTP Requests duration (percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ipld_eth_server_http_duration_bucket[1m]))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.75, rate(ipld_eth_server_http_duration_bucket[1m]))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, rate(ipld_eth_server_http_duration_bucket[1m]))",
     "legendFormat": "0.5"
    }
   ]
  }
 ]
}