name: Docker Build

on: [pull_request]
jobs:
  run-tests:
    uses: ./.github/workflows/tests.yaml
    secrets:
      BUILD_HOSTNAME: ${{ secrets.BUILD_HOSTNAME }}
      BUILD_USERNAME: ${{ secrets.BUILD_USERNAME }}
      BUILD_KEY: ${{ secrets.BUILD_KEY }}
