name: Test, Build, and/or Publish
on:
  release:
    types: [published]
  pull_request:

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          do_not_skip: '["workflow_dispatch", "schedule"]'
  run-tests:
    uses: ./.github/workflows/tests.yaml
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    needs: pre_job
    secrets:
      BUILD_HOSTNAME: ${{ secrets.BUILD_HOSTNAME }}
      BUILD_USERNAME: ${{ secrets.BUILD_USERNAME }}
      BUILD_KEY: ${{ secrets.BUILD_KEY }}
    with:
      STACK_ORCHESTRATOR_REF: "f2fd766f5400fcb9eb47b50675d2e3b1f2753702"
      GO_ETHEREUM_REF: "2ddad81c1a04ff494a706f2f757a0f75d2616fbd"
      IPLD_ETH_DB_REF: "d4d704616ba0f87733853c78787bf54c9868d2ac"
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    needs: run-tests
    if: |
      always() &&
      (needs.run-tests.result == 'success' || needs.run-tests.result == 'skipped') &&
      github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: |
          echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
          echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})
      - name: Run docker build
        run: make docker-build
      - name: Tag docker image SHA
        run: docker tag cerc-io/ipld-eth-server git.vdb.to/cerc-io/ipld-eth-server/ipld-eth-server:${{steps.vars.outputs.sha}}
      - name: Tag docker image TAG
        run: docker tag git.vdb.to/cerc-io/ipld-eth-server/ipld-eth-server:${{steps.vars.outputs.sha}} git.vdb.to/cerc-io/ipld-eth-server/ipld-eth-server:${{steps.vars.outputs.tag}}
      - name: Docker Login
        run: echo ${{ secrets.GITEA_TOKEN }} | docker login https://git.vdb.to -u cerccicd --password-stdin
      - name: Docker Push SHA
        run: docker push git.vdb.to/cerc-io/ipld-eth-server/ipld-eth-server:${{steps.vars.outputs.sha}}
      - name: Docker Push TAG
        run: docker push git.vdb.to/cerc-io/ipld-eth-server/ipld-eth-server:${{steps.vars.outputs.tag}}
