name: Test, Build, and/or Publish
on:
  release:
    types: [published]
  pull_request:

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      # should_skip: ${{ steps.skip_check.outputs.should_skip }}
      should_skip: false # XXX dev
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          do_not_skip: '["workflow_dispatch", "schedule"]'
  run-tests:
    uses: ./.github/workflows/tests.yaml
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    needs: pre_job
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    needs: run-tests
    if: |
      always() &&
      (needs.run-tests.result == 'success' || needs.run-tests.result == 'skipped') &&
      github.event_name == 'release'
    steps:
      - uses: actions/checkout@v3
      - id: vars
        name: Output SHA and version tag
        run: |
          echo sha=$(echo ${GITHUB_SHA:0:7}) >> "$GITHUB_OUTPUT"
          echo tag=$(echo ${GITHUB_REF#refs/tags/}) >> "$GITHUB_OUTPUT""
      - name: Build and tag Docker image
        run: |
          docker build . \
          -t cerc-io/ipld-eth-server \
          -t git.vdb.to/cerc-io/ipld-eth-server/ipld-eth-server:${{steps.vars.outputs.sha}} \
          -t git.vdb.to/cerc-io/ipld-eth-server/ipld-eth-server:${{steps.vars.outputs.tag}}
      - name: Push Docker tags
        run: |
          echo ${{ secrets.GITEA_TOKEN }} | docker login https://git.vdb.to -u cerccicd --password-stdin
          docker push git.vdb.to/cerc-io/ipld-eth-server/ipld-eth-server:${{steps.vars.outputs.sha}}
          docker push git.vdb.to/cerc-io/ipld-eth-server/ipld-eth-server:${{steps.vars.outputs.tag}}
